# -*- coding: utf-8 -*-
"""Summary.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dEXSG490FpLPH5aFk-ok1mvDdnNpA7W0
"""

# !pip install pymongo
from transformers import pipeline
import pandas as pd
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi
from textblob import TextBlob
import matplotlib.pyplot as plt
from transformers import pipeline

uri = "mongodb+srv://selecto:DmdSvpAnRnudk1Zj@reviews-list.q56a6p2.mongodb.net/?retryWrites=true&w=majority"
client = MongoClient(uri, server_api=ServerApi('1'))
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

db = client['Reviews']
collection = db['Pixel 7a - 128GB - Charcoal Pixel Buds A-Series - Charcoal']

summarizer = pipeline("summarization", model="sshleifer/distilbart-cnn-12-6", revision="a4f8f3e")
all_reviews_text = "\n".join(reviews)
max_chunk_size = 1000
chunks = [all_reviews_text[i:i+max_chunk_size] for i in range(0, len(all_reviews_text), max_chunk_size)]
summaries = []
for chunk in chunks:
    summary_chunk = summarizer(chunk, max_length=150, min_length=50, length_penalty=2.0, num_beams=4, early_stopping=True)
    summaries.append(summary_chunk[0]['summary_text'])
final_summary = " ".join(summaries)
print("Generated Summary:")
print(final_summary)